name: FriCAS CI on Linux on CLISP

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-24.04
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install clisp libxpm-dev

    - name: configure
      run: ./configure --with-lisp=clisp --with-x || cat config.log

    - name: make
      run: make -j4 --output-sync

    - name: make check
      run: make check -j4 --output-sync

    - name: Create artifact archives
      run: |
        test "$GITHUB_REF_TYPE" != "tag" && rm -r target/*/src
        tar -cjf FriCAS-linux-x86_64-${{ github.sha }}.tar.bz2 target/

    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: FriCAS-linux-x86_64-binary
        path: FriCAS-linux-x86_64-${{ github.sha }}.tar.bz2

    - name: Upload to nightly release
      if: ${{ github.event_name == 'push' && ( github.event.ref == 'refs/heads/master' || github.ref_type == 'tag' ) && github.repository == 'fricas/fricas' }}
      ## RELEASE_ID is:
      ## `curl https://api.github.com/${REPO_URL}/tags/nightly | jq .id`
      run: |
        export REPO_URL=repos/fricas/fricas-nightly-builds/releases
        export RELEASE_ID=74905307
        export TIMESTAMP=$(date +%Y-%m-%dT%H.%M)
        export SHA=$(echo ${{ github.sha }} | cut -c 1-8)
        export FILENAME1=FriCAS-${TIMESTAMP}-linux-x86_64-${SHA}.tar.bz2
        export FILENAME2=fricas-${GITHUB_REF_NAME}-linux-x86_64.tar.bz2
        export FILENAME=$(test "$GITHUB_REF_TYPE" != "tag" && echo $FILENAME1 || echo $FILENAME2)
        export URL=https://uploads.github.com/${REPO_URL}/${RELEASE_ID}/assets
        curl -v -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.releasetoken }}" \
            "${URL}?name=${FILENAME}" \
            --data-binary "@FriCAS-linux-x86_64-${{ github.sha }}.tar.bz2" \
            -H "Content-Type: application/x-bzip2" || true
