name: FriCAS CI on Linux on GCL

on: [push, pull_request, workflow_dispatch]
permissions: {}

jobs:
  build:
    if: contains(github.event.head_commit.message, 'gcl') || github.event_name == 'workflow_dispatch'

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    env:
      ARCH: ${{ matrix.os == 'ubuntu-24.04' && 'x86-64' || 'arm64' }}

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcl libxpm-dev libreadline-dev

    - name: configure and make
      run: |
        export GCL_ANSI=t
        ./configure --with-lisp=gcl --with-x || cat config.log
        make -j4 --output-sync

    - name: make check
      run: make check -j4 --output-sync

    - name: Create artifact archives
      run: |
        test "$GITHUB_REF_TYPE" != "tag" && rm -r target/*/src
        tar -cjf FriCAS-linux-GCL-${{ env.ARCH }}-${{ github.sha }}.tar.bz2 target/

    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: FriCAS-linux-GCL-${{ env.ARCH }}-binary
        path: FriCAS-linux-GCL-${{ env.ARCH }}-${{ github.sha }}.tar.bz2
