name: FriCAS CI on Linux

on: [push, pull_request]
permissions: {}

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      ARCH: ${{ matrix.os == 'ubuntu-24.04' && 'x86-64' || 'arm64' }}

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install sbcl libgmp-dev libxpm-dev

    - name: configure
      run: ./configure --with-lisp=sbcl --with-gmp --with-x || cat config.log

    - name: make
      run: make -j4 --output-sync

    - name: make check
      run: make check -j4 --output-sync

    - name: Create artifact archives
      run: |
        test "$GITHUB_REF_TYPE" != "tag" && rm -r target/*/src
        tar -cjf FriCAS-linux-${ARCH}-${{ github.sha }}.tar.bz2 target/

    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: FriCAS-linux-${{ env.ARCH }}-binary
        path: FriCAS-linux-${{ env.ARCH }}-${{ github.sha }}.tar.bz2

    - name: make book
      if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
      run: |
        sudo apt-get install xvfb texlive-font-utils texlive-latex-extra texlive-science
        export SOURCE_DATE_EPOCH=`date -u -d "today 00:00:00" +%s`
        make -j4 book

    - name: Upload reference book
      if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
      uses: actions/upload-artifact@v4
      with:
        name: fricas-reference-book-${{ env.ARCH }}
        path: src/doc/book.pdf

    - name: Upload to nightly release
      if: ${{ github.event_name == 'push' && ( github.event.ref == 'refs/heads/master' || github.ref_type == 'tag' ) && github.repository == 'fricas/fricas' }}
      ## RELEASE_ID is:
      ## `curl https://api.github.com/${REPO_URL}/tags/nightly | jq .id`
      run: |
        export REPO_URL=repos/fricas/fricas-nightly-builds/releases
        export RELEASE_ID=74905307
        export TIMESTAMP=$(date +%Y-%m-%dT%H.%M)
        export SHA=$(echo ${{ github.sha }} | cut -c 1-8)
        export FILENAME1=FriCAS-${TIMESTAMP}-linux-${ARCH}-${SHA}.tar.bz2
        export FILENAME2=fricas-${GITHUB_REF_NAME}-linux-${ARCH}.tar.bz2
        export FILENAME=$(test "$GITHUB_REF_TYPE" != "tag" && echo $FILENAME1 || echo $FILENAME2)
        export URL=https://uploads.github.com/${REPO_URL}/${RELEASE_ID}/assets
        curl -v -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.releasetoken }}" \
            "${URL}?name=${FILENAME}" \
            --data-binary "@FriCAS-linux-${ARCH}-${{ github.sha }}.tar.bz2" \
            -H "Content-Type: application/x-bzip2" || true
