name: FriCAS CI on Linux on CCL

on: [push, pull_request, workflow_dispatch]
permissions: {}

jobs:
  build:
    if: contains(github.event.head_commit.message, 'ccl') || contains(github.event.head_commit.message, 'clozure') || github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgmp-dev libxpm-dev
        wget https://github.com/Clozure/ccl/releases/download/v1.13/ccl-1.13-linuxx86.tar.gz
        tar xvf ccl-1.13-linuxx86.tar.gz

    - name: configure
      run: ./configure --with-lisp=`pwd`/ccl/lx86cl64 --with-gmp --with-x || cat config.log

    - name: make
      run: make -j4 --output-sync

    - name: make check
      run: make check -j4 --output-sync

    - name: Create artifact archives
      run: |
        test "$GITHUB_REF_TYPE" != "tag" && rm -r target/*/src
        tar -cjf FriCAS-linux-CCL-x86_64-${{ github.sha }}.tar.bz2 target/

    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: FriCAS-linux-CCL-x86_64-binary
        path: FriCAS-linux-CCL-x86_64-${{ github.sha }}.tar.bz2
