name: FriCAS CI on macOS on CCL

on: [push, pull_request, workflow_dispatch]
permissions: {}

jobs:
  build:
    if: contains(github.event.head_commit.message, 'ccl') || contains(github.event.head_commit.message, 'clozure') || github.event_name == 'workflow_dispatch'

    runs-on: macos-13
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: |
        brew install clozure-cl
        mkdir ../build && cd ../build
        ../fricas/configure --with-lisp=ccl64 --with-gmp=`brew --prefix` || cat config.log

    - name: make
      run: cd ../build && make -j4

    - name: make check
      run: cd ../build && make check -j4

    - name: Create artifact archives
      run: |
        cd ../build
        test "$GITHUB_REF_TYPE" != "tag" && rm -r target/*/src
        make dist-macos
        cp -v `brew list gmp | grep libgmp.10.dylib` FriCAS.app/Contents/Resources/usr/local/lib/fricas/target/*/lib/
        ## reduce chance of error caused by "hdiutil: Resource busy"
        make dist-macos-dmg || make dist-macos-dmg
        mv FriCAS.dmg ../fricas/FriCAS-macOS-CCL-x86_64-${{ github.sha }}.dmg

    - name: Upload macOS binary
      uses: actions/upload-artifact@v4
      with:
        name: FriCAS-macOS-CCL-x86_64-binary
        path: FriCAS-macOS-CCL-x86_64-${{ github.sha }}.dmg
