name: FriCAS CI on macOS

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, macos-14]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      SBCL_VER: ${{ matrix.os == 'macos-13' && '2.2.9' || '2.4.0' }}
      ARCH: ${{ matrix.os == 'macos-13' && 'x86-64' || 'arm64' }}

    steps:
    - uses: actions/checkout@v4
    - name: download and install SBCL
      run: |
        brew install buildapp
        brew install cafeobj
