name: FriCAS CI on Windows on CCL

on: [push, pull_request, workflow_dispatch]
permissions: {}

jobs:
  build:
    if: contains(github.event.head_commit.message, 'ccl') || contains(github.event.head_commit.message, 'clozure') || github.event_name == 'workflow_dispatch'

    runs-on: windows-2022
    timeout-minutes: 30
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: make mingw-w64-x86_64-gcc mingw-w64-x86_64-gmp gmp-devel zip unzip

    - uses: actions/checkout@v4
    - name: configure and make
      run: |
        mkdir ../build && cd ../build
        wget https://github.com/Clozure/ccl/releases/download/v1.13/ccl-1.13-windowsx86.zip
        unzip ccl-1.13-windowsx86.zip
        ../fricas/configure --with-lisp=`pwd`/ccl/wx86cl64.exe --enable-gmp || cat config.log
        make -j4 --output-sync

    - name: make check
      run: cd ../build && make check -j4 --output-sync

    - name: Create artifact archives
      run: |
        test "$GITHUB_REF_TYPE" != "tag" && rm -r ../build/target/*/src
        rm ../build/target/x86_64-w64-mingw32/bin/{fricas,fricas-readline}
        mv ../build/target/x86_64-w64-mingw32 FriCAS-windows-x86_64
        cp /mingw64/bin/libgmp-10.dll FriCAS-windows-x86_64/lib/
        zip -r FriCAS-windows-CCL-x86_64-${{ github.sha }}.zip FriCAS-windows-x86_64

    - name: Upload Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: FriCAS-windows-CCL-x86_64-binary
        path: FriCAS-windows-CCL-x86_64-${{ github.sha }}.zip
